#!/bin/bash
composer install --ignore-platform-reqs && \
mkdir temp && \
cd temp && \
  wget -c "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz" && \
  tar xf ffmpeg-release-amd64-static.tar.xz && \
  cp ffmpeg-*-amd64-static/ffmpeg ../bin/ && \
  wget -c "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.4.1-linux-x86-64.tar.gz" && \
  tar xzvf && \
  cp libwebp-0.4.1-linux-x86-64/bin/cwebp ../bin/ && \
  cd .. && \
docker build -t chequeas-api . 

